#!/usr/bin/env bash
set -o nounset
set -o pipefail
set -e
root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
archive=$(mktemp)
output=$(mktemp)
trap 'rm -f -- "$archive" "$output"' EXIT
(cd "$root" && COPYFILE_DISABLE=1 tar -czf "$archive" bin integrations config scripts/prompt-key.bash install.sh install-macos.sh uninstall.sh README.md LICENSE CHANGELOG.md)
if command -v shasum >/dev/null 2>&1; then
    checksum=$(shasum -a 256 "$archive" | cut -d ' ' -f 1)
else
    checksum=$(sha256sum "$archive" | cut -d ' ' -f 1)
fi
cat > "$output" <<'HEADER'
#!/usr/bin/env bash
# Generated by scripts/build-online-installer.sh. Review source before piping to Bash.
set -o nounset
set -o pipefail
set -e
temp=$(mktemp -d)
trap 'rm -rf -- "$temp"' EXIT
base64 -d > "$temp/ai-shell.tar.gz" <<'AI_SHELL_BUNDLE'
HEADER
base64 < "$archive" >> "$output"
cat >> "$output" <<'FOOTER'
AI_SHELL_BUNDLE
if command -v shasum >/dev/null 2>&1; then
    actual_sha=$(shasum -a 256 "$temp/ai-shell.tar.gz" | cut -d ' ' -f 1)
else
    actual_sha=$(sha256sum "$temp/ai-shell.tar.gz" | cut -d ' ' -f 1)
fi
[[ $actual_sha == "$expected_sha" ]] || { printf 'ai-shell: installer payload checksum mismatch\n' >&2; exit 2; }
tar -xzf "$temp/ai-shell.tar.gz" -C "$temp"
if [[ $(uname -s) == Darwin ]]; then
    bash "$temp/install-macos.sh" --prompt-key
else
    bash "$temp/install.sh" --prompt-key
fi
FOOTER
# Insert the checksum before code that checks it.
sed "s/^AI_SHELL_BUNDLE$/AI_SHELL_BUNDLE\nexpected_sha=$checksum/" "$output" > "$root/install-online.sh"
chmod 755 "$root/install-online.sh"
printf 'Built %s (payload SHA-256 %s)\n' "$root/install-online.sh" "$checksum"
